-- AdventureWorks AI Enhancements
-- This script applies schema modifications to support AI-enhanced product data

-- Increase ProductDescription.Description column size to accommodate AI-generated content
-- Original: nvarchar(400) - Too small for enhanced descriptions (AI generates ~500+ characters)
-- Updated: nvarchar(2000) - Allows for detailed AI-generated product descriptions

-- Step 1: Drop the dependent indexed view
IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vProductAndDescription]'))
BEGIN
    DROP VIEW [Production].[vProductAndDescription];
    PRINT 'Dropped view Production.vProductAndDescription';
END;

GO

-- Step 2: Alter the Description column
ALTER TABLE [Production].[ProductDescription]
ALTER COLUMN [Description] [nvarchar](2000) NOT NULL;

PRINT 'ProductDescription.Description column updated to nvarchar(2000)';

GO

-- Step 3: Recreate the indexed view
CREATE VIEW [Production].[vProductAndDescription] 
WITH SCHEMABINDING 
AS 
-- View (indexed or standard) to display products and product descriptions by language.
SELECT 
    p.[ProductID] 
    ,p.[Name] 
    ,pm.[Name] AS [ProductModel] 
    ,pmx.[CultureID] 
    ,pd.[Description] 
FROM [Production].[Product] p 
    INNER JOIN [Production].[ProductModel] pm 
    ON p.[ProductModelID] = pm.[ProductModelID] 
    INNER JOIN [Production].[ProductModelProductDescriptionCulture] pmx 
    ON pm.[ProductModelID] = pmx.[ProductModelID] 
    INNER JOIN [Production].[ProductDescription] pd 
    ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID];

GO

-- Step 4: Recreate the clustered index on the view
CREATE UNIQUE CLUSTERED INDEX [IX_vProductAndDescription] ON [Production].[vProductAndDescription]([CultureID], [ProductID]);

GO

PRINT 'Successfully recreated view Production.vProductAndDescription with clustered index';

GO

-- Step 5: Expand Product.Color column to support creative AI-generated color names
-- Original: nvarchar(15) - Too restrictive for descriptive color names (e.g., "Glossy Carbon Fiber")
-- Updated: nvarchar(256) - Allows for detailed AI-generated color descriptions

ALTER TABLE [Production].[Product]
ALTER COLUMN [Color] [nvarchar](256) NULL;

PRINT 'Product.Color column updated to nvarchar(256)';

GO

-- Step 6: Add vector embedding column to ProductDescription for semantic search
-- Embeddings generated by text-embedding-3-small model (1536 dimensions)
-- Stored as VARBINARY(MAX) for Azure SQL Database vector search
-- Size: 1536 dimensions × 4 bytes (float32) = 6144 bytes per embedding
-- Embeddings stored per language - enables multi-language semantic search

ALTER TABLE [Production].[ProductDescription]
ADD [DescriptionEmbedding] VARBINARY(MAX) NULL;

PRINT 'ProductDescription.DescriptionEmbedding column added for vector embeddings';

GO

-- Step 7: Create view for semantic product search across all languages
-- Joins Product -> ProductModel -> ProductModelProductDescriptionCulture -> ProductDescription
-- Enables language-specific vector similarity search via DAB API

CREATE VIEW [Production].[vProductSearch]
AS
SELECT 
    p.[ProductID],
    p.[Name] AS [ProductName],
    p.[ProductNumber],
    p.[Color],
    p.[Size],
    p.[Weight],
    p.[ListPrice],
    p.[ProductModelID],
    pm.[Name] AS [ProductModelName],
    pmx.[CultureID],
    pmx.[ProductDescriptionID],
    pd.[Description],
    pd.[DescriptionEmbedding],
    p.[ModifiedDate]
FROM [Production].[Product] p
    LEFT JOIN [Production].[ProductModel] pm 
        ON p.[ProductModelID] = pm.[ProductModelID]
    LEFT JOIN [Production].[ProductModelProductDescriptionCulture] pmx 
        ON pm.[ProductModelID] = pmx.[ProductModelID]
    LEFT JOIN [Production].[ProductDescription] pd 
        ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID]
WHERE p.[FinishedGoodsFlag] = 1;

GO

PRINT 'Created view Production.vProductSearch for multi-language semantic search';

GO

PRINT 'AI enhancements applied successfully';
