-- AdventureWorks AI Enhancements
-- This script applies schema modifications to support AI-enhanced product data

-- Increase ProductDescription.Description column size to accommodate AI-generated content
-- Original: nvarchar(400) - Too small for enhanced descriptions (AI generates ~500+ characters)
-- Updated: nvarchar(2000) - Allows for detailed AI-generated product descriptions

-- Step 1: Drop the dependent indexed view
IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vProductAndDescription]'))
BEGIN
    DROP VIEW [Production].[vProductAndDescription];
    PRINT 'Dropped view Production.vProductAndDescription';
END;

GO

-- Step 2: Alter the Description column
ALTER TABLE [Production].[ProductDescription]
ALTER COLUMN [Description] [nvarchar](2000) NOT NULL;

PRINT 'ProductDescription.Description column updated to nvarchar(2000)';

GO

-- Step 3: Recreate the indexed view
CREATE VIEW [Production].[vProductAndDescription] 
WITH SCHEMABINDING 
AS 
-- View (indexed or standard) to display products and product descriptions by language.
SELECT 
    p.[ProductID] 
    ,p.[Name] 
    ,pm.[Name] AS [ProductModel] 
    ,pmx.[CultureID] 
    ,pd.[Description] 
FROM [Production].[Product] p 
    INNER JOIN [Production].[ProductModel] pm 
    ON p.[ProductModelID] = pm.[ProductModelID] 
    INNER JOIN [Production].[ProductModelProductDescriptionCulture] pmx 
    ON pm.[ProductModelID] = pmx.[ProductModelID] 
    INNER JOIN [Production].[ProductDescription] pd 
    ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID];

GO

-- Step 4: Recreate the clustered index on the view
CREATE UNIQUE CLUSTERED INDEX [IX_vProductAndDescription] ON [Production].[vProductAndDescription]([CultureID], [ProductID]);

GO

PRINT 'Successfully recreated view Production.vProductAndDescription with clustered index';

GO

-- Step 5: Expand Product.Color column to support creative AI-generated color names
-- Original: nvarchar(15) - Too restrictive for descriptive color names (e.g., "Glossy Carbon Fiber")
-- Updated: nvarchar(256) - Allows for detailed AI-generated color descriptions

ALTER TABLE [Production].[Product]
ALTER COLUMN [Color] [nvarchar](256) NULL;

PRINT 'Product.Color column updated to nvarchar(256)';

GO

-- Step 6: Add vector embedding column to ProductDescription for semantic search
-- Embeddings generated by text-embedding-3-small model (1536 dimensions)
-- Stored as VECTOR(1536) for Azure SQL Database native vector search
-- Size: 1536 dimensions × 4 bytes (float32) = 6144 bytes per embedding
-- Embeddings stored per language - enables multi-language semantic search

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductDescription]') AND name = 'DescriptionEmbedding')
BEGIN
    ALTER TABLE [Production].[ProductDescription]
    ADD [DescriptionEmbedding] VECTOR(1536) NULL;
    
    PRINT 'ProductDescription.DescriptionEmbedding column added for vector embeddings';
END
ELSE
BEGIN
    PRINT 'ProductDescription.DescriptionEmbedding column already exists - skipping';
END;

GO

-- Step 7: Create view for semantic product search across all languages
-- Joins Product -> ProductModel -> ProductModelProductDescriptionCulture -> ProductDescription
-- Enables language-specific vector similarity search via DAB API
-- Always drop and recreate to ensure view stays current with schema changes

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vProductSearch]'))
BEGIN
    DROP VIEW [Production].[vProductSearch];
END;

GO

CREATE VIEW [Production].[vProductSearch]
AS
SELECT 
        p.[ProductID],
        p.[Name] AS [ProductName],
        p.[ProductNumber],
        p.[Color],
        p.[Size],
        p.[Weight],
        p.[ListPrice],
        p.[ProductModelID],
        pm.[Name] AS [ProductModelName],
        pmx.[CultureID],
        pmx.[ProductDescriptionID],
        pd.[Description],
        pd.[DescriptionEmbedding],
        p.[ModifiedDate]
    FROM [Production].[Product] p
        LEFT JOIN [Production].[ProductModel] pm 
            ON p.[ProductModelID] = pm.[ProductModelID]
        LEFT JOIN [Production].[ProductModelProductDescriptionCulture] pmx 
            ON pm.[ProductModelID] = pmx.[ProductModelID]
        LEFT JOIN [Production].[ProductDescription] pd 
            ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID]
    WHERE p.[FinishedGoodsFlag] = 1;

GO
    
PRINT 'Created view Production.vProductSearch for multi-language semantic search';

GO

-- Step 8: Remove all references to ProductPhotoID 1 (placeholder image)
-- This clears out the old placeholder photo that was used before AI-generated images

DELETE FROM [Production].[ProductProductPhoto]
WHERE [ProductPhotoID] = 1;

PRINT 'Removed all ProductProductPhoto records referencing ProductPhotoID 1';

GO

-- Step 9: Set Primary photo to most recent (box shot) for all products
-- The GenerateProductImages function creates box shots with the most recent ModifiedDate
-- Update Primary flag: set most recent photo to Primary (1), all others to non-Primary (0)

WITH RankedPhotos AS (
    SELECT 
        ProductID,
        ProductPhotoID,
        ROW_NUMBER() OVER (PARTITION BY ProductID ORDER BY ModifiedDate DESC) as PhotoRank
    FROM [Production].[ProductProductPhoto]
)
UPDATE pp
SET pp.[Primary] = CASE WHEN rp.PhotoRank = 1 THEN 1 ELSE 0 END
FROM [Production].[ProductProductPhoto] pp
INNER JOIN RankedPhotos rp 
    ON pp.ProductID = rp.ProductID 
    AND pp.ProductPhotoID = rp.ProductPhotoID;

PRINT 'Updated Primary flag: most recent photo (box shot) set as Primary for all products';

GO

-- Step 10: Add vector embedding column to ProductReview for semantic search
-- Embeddings generated by text-embedding-3-small model (1536 dimensions)
-- Stored as VECTOR(1536) for Azure SQL Database native vector search
-- Size: 1536 dimensions × 4 bytes (float32) = 6144 bytes per embedding
-- Enables semantic search across product review comments

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'CommentsEmbedding')
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD [CommentsEmbedding] VECTOR(1536) NULL;
    
    PRINT 'ProductReview.CommentsEmbedding column added for vector embeddings';
END
ELSE
BEGIN
    PRINT 'ProductReview.CommentsEmbedding column already exists - skipping';
END;

GO

-- Step 11: Add helpful vote counter to ProductReview
-- Tracks the number of "helpful" votes each review receives from customers
-- Defaults to 0 for all existing and new reviews
-- Useful for sorting and displaying most helpful reviews

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'HelpfulVotes')
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD [HelpfulVotes] INT NOT NULL DEFAULT 0;
    
    PRINT 'ProductReview.HelpfulVotes column added for tracking helpful votes';
END
ELSE
BEGIN
    PRINT 'ProductReview.HelpfulVotes column already exists - skipping';
END;

GO

-- Step 12: Add UserID column to ProductReview
-- Stores the BusinessEntityID to link reviews to user accounts in Person.Person table
-- Nullable to preserve existing reviews that don't have a UserID
-- Enables features like: preventing duplicate reviews, edit/delete own reviews, and tracking user activity

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'UserID')
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD [UserID] INT NULL;
    
    PRINT 'ProductReview.UserID column added for linking reviews to user accounts';
END
ELSE
BEGIN
    PRINT 'ProductReview.UserID column already exists - skipping';
END;

GO

-- Step 12a: Add foreign key constraint to Person.Person
-- Links UserID directly to the Person table via BusinessEntityID
-- This enforces referential integrity - reviews can only reference valid users

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[Production].[FK_ProductReview_Person_UserID]'))
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD CONSTRAINT [FK_ProductReview_Person_UserID]
    FOREIGN KEY ([UserID]) REFERENCES [Person].[Person]([BusinessEntityID]);
    
    PRINT 'Added foreign key constraint linking UserID to Person.BusinessEntityID';
END
ELSE
BEGIN
    PRINT 'Foreign key constraint FK_ProductReview_Person_UserID already exists - skipping';
END;

GO

-- Step 12b: Add unique constraint to prevent duplicate reviews per user
-- Ensures each user can only submit one review per product
-- Filtered to exclude legacy reviews that don't have a UserID

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'IX_ProductReview_ProductID_UserID_Unique')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [IX_ProductReview_ProductID_UserID_Unique]
    ON [Production].[ProductReview]([ProductID], [UserID])
    WHERE [UserID] IS NOT NULL;
    
    PRINT 'Added unique constraint on (ProductID, UserID) to prevent duplicate reviews';
END
ELSE
BEGIN
    PRINT 'Unique index IX_ProductReview_ProductID_UserID_Unique already exists - skipping';
END;

GO

-- Step 12c: Add index on UserID for query performance
-- Enables efficient lookup of all reviews by a specific user

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'IX_ProductReview_UserID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ProductReview_UserID]
    ON [Production].[ProductReview]([UserID])
    WHERE [UserID] IS NOT NULL;
    
    PRINT 'Added index on UserID for improved query performance';
END
ELSE
BEGIN
    PRINT 'Index IX_ProductReview_UserID already exists - skipping';
END;

GO

-- Step 13: Create view for semantic review search
-- Enables vector similarity search on product reviews via DAB API
-- Useful for finding reviews based on semantic meaning rather than keyword matching
-- Always drop and recreate to ensure view stays current with schema changes

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vReviewSearch]'))
BEGIN
    DROP VIEW [Production].[vReviewSearch];
END;

GO

CREATE VIEW [Production].[vReviewSearch]
AS
SELECT 
        pr.[ProductReviewID],
        pr.[ProductID],
        pr.[ReviewerName],
        pr.[ReviewDate],
        pr.[Rating],
        pr.[Comments],
        pr.[CommentsEmbedding],
        pr.[HelpfulVotes],
        pr.[UserID],
        pr.[ModifiedDate],
        p.[Name] AS [ProductName],
        p.[ProductNumber]
    FROM [Production].[ProductReview] pr
        INNER JOIN [Production].[Product] p 
            ON pr.[ProductID] = p.[ProductID];

GO
    
PRINT 'Created view Production.vReviewSearch for semantic review search';

GO

PRINT 'AI enhancements applied successfully';
