#!/bin/bash

# Setup script to configure the local development environment
# This script extracts Azure resource information and sets up the DATABASE_CONNECTION_STRING

echo "Setting up local development environment..."

# Get Azure environment variables
cd /workspaces/AdventureWorks

# Extract SQL Server information
SQL_SERVER=$(azd env get-values | grep "SQL_SERVER_NAME=" | cut -d'=' -f2 | tr -d '"')
SQL_DATABASE=$(azd env get-values | grep "SQL_DATABASE_NAME=" | cut -d'=' -f2 | tr -d '"')

echo "Found SQL Server: $SQL_SERVER"
echo "Found Database: $SQL_DATABASE"

if [ -z "$SQL_SERVER" ] || [ -z "$SQL_DATABASE" ]; then
    echo "Error: Could not find SQL Server information from azd environment"
    echo "Make sure you've run 'azd provision' or 'azd up' first"
    exit 1
fi

# Build connection string
# Note: This uses Azure AD authentication (managed identity)
# For local development, you'll need to be logged into Azure CLI
CONNECTION_STRING="Server=${SQL_SERVER}.database.windows.net;Database=${SQL_DATABASE};Authentication=Active Directory Default;"

echo ""
echo "Connection string generated:"
echo "$CONNECTION_STRING"
echo ""

# Export for current session
export DATABASE_CONNECTION_STRING="$CONNECTION_STRING"

# Save to a local .env file for the API
cat > /workspaces/AdventureWorks/api/.env << EOF
# Generated by setup-local-dev.sh
# This file is git-ignored and safe for local development

DATABASE_CONNECTION_STRING="${CONNECTION_STRING}"
EOF

echo "✓ Created /workspaces/AdventureWorks/api/.env"
echo ""
echo "DATABASE_CONNECTION_STRING has been set for this terminal session."
echo ""
echo "To use in other terminals, run:"
echo "  export DATABASE_CONNECTION_STRING=\"$CONNECTION_STRING\""
echo ""
echo "Or source the .env file:"
echo "  cd /workspaces/AdventureWorks/api"
echo "  export \$(cat .env | xargs)"
echo ""
echo "You're now ready to start the local API server:"
echo "  cd /workspaces/AdventureWorks/api"
echo "  ./start-local-api.sh"
