// <auto-generated>
// Source of truth: docs/features/functions-oauth/ROUTE_SCOPE_MATRIX.md
// Regenerate with the Phase A/C extractor if the Functions HTTP surface changes, then keep this
// registry and that matrix in lock-step. A reflection-based coverage check at startup
// (ValidateCoverage) fails fast if any HTTP function is missing an entry here.
// </auto-generated>
#nullable enable
using System.Collections.Frozen;

namespace ApiFunctions.Auth;

/// <summary>
/// Authoritative, per-function authorization policy for every api-functions HTTP route (187
/// routes). Keyed by the <c>[Function]</c> name. Mirrors the committed route-to-scope matrix and
/// the pattern of api-mcp's <c>ToolAuthorizationRegistry</c>.
/// </summary>
public static class FunctionAuthorizationRegistry
{
    private static readonly FrozenDictionary<string, FunctionPolicy> Policies = new FunctionPolicy[]
    {
        // ---- Tier P — anonymous (18) ----
        new("AIAgentChat", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/agent/chat
        new("AIAgentStatus", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/agent/status
        new("GetOpenApiSpec", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/openapi.json
        new("GetSearchSuggestions", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/search/suggestions
        new("GetSitemap", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/sitemap.xml
        new("GetSwaggerUI", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/swagger/ui
        new("HealthCheck", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/health
        new("HelpMeChooseCatalogMeta", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/helpme/catalog-meta
        new("HelpMeChooseQuestions", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/helpme/questions
        new("HelpMeChooseRecommend", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/helpme/recommend
        new("NegotiateWebPubSub", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/webpubsub/negotiate
        new("RequestPasswordReset", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/password/reset/request
        new("ResetPassword", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/password/reset/complete
        new("SeedJobStatus", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/seed/status
        new("SemanticSearch", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/search/semantic
        new("SetPassword", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/password
        new("ValidateResetToken", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/password/reset/validate
        new("VerifyPassword", AccessTier.Public, null, AccessMode.Anonymous, null),  // /api/password/verify

        // ---- Tier C — consumer self-or-internal, ownership (9) ----
        new("CheckOrderReceipt", AccessTier.Consumer, FunctionScopes.OrdersRead, AccessMode.SelfOrInternal, "salesOrderId(owner CustomerID)"),  // /api/orders/{salesOrderId:int}/receipt-status
        new("CreateAddress", AccessTier.Consumer, FunctionScopes.CustomersWrite, AccessMode.SelfOrInternal, "businessEntityId"),  // /api/addresses
        new("DeleteAddress", AccessTier.Consumer, FunctionScopes.CustomersWrite, AccessMode.SelfOrInternal, "businessEntityId"),  // /api/addresses/{id:int}
        new("DownloadOrderReceipt", AccessTier.Consumer, FunctionScopes.OrdersRead, AccessMode.SelfOrInternal, "salesOrderId(owner CustomerID)"),  // /api/orders/{salesOrderId:int}/receipt
        new("GenerateAndSendReceipt", AccessTier.Consumer, FunctionScopes.OrdersRead, AccessMode.SelfOrInternal, "salesOrderId(owner CustomerID)"),  // /api/orders/generate-and-send-receipt
        new("GetAddressById", AccessTier.Consumer, FunctionScopes.CustomersRead, AccessMode.SelfOrInternal, "businessEntityId"),  // /api/addresses/{id:int}
        new("GetAddresses", AccessTier.Consumer, FunctionScopes.CustomersRead, AccessMode.SelfOrInternal, "businessEntityId"),  // /api/addresses
        new("GetPersonAddresses", AccessTier.Consumer, FunctionScopes.CustomersRead, AccessMode.SelfOrInternal, "businessEntityId"),  // /api/person-addresses
        new("UpdateAddress", AccessTier.Consumer, FunctionScopes.CustomersWrite, AccessMode.SelfOrInternal, "businessEntityId"),  // /api/addresses/{id:int}

        // ---- Tier I — internal-only (116) ----
        new("AIJobQueue_Status", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/ai-job-queue/status
        new("AnalyzeCartRecovery", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/carts/analyze-recovery
        new("AnalyzeReviewsBatch", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/reviews/analyze-batch
        new("ApproveAllManufacturingProposals", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/proposals/approve-all
        new("ApproveManufacturingProposal", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/proposals/{id}/approve
        new("ArchiveTransactionHistoryHttp", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/archive/trigger
        new("AutoPromotion_GetConfig", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/auto-promotion/config
        new("AutoPromotion_ResetCounters", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/auto-promotion/reset-counters
        new("AutoPromotion_UpdateConfig", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/auto-promotion/config
        new("BankGetAccounts", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/bank/accounts
        new("BeginProcessingOrder", AccessTier.Internal, FunctionScopes.OrdersWrite, AccessMode.InternalOnly, null),  // /api/orders/begin-processing-order
        new("ClearManufacturingAgentPoisonQueue", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/agent-queue/poison
        new("ClearManufacturingAgentQueue", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/agent-queue
        new("CreateCategory", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/CreateCategory
        new("CreateSubcategory", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/CreateSubcategory
        new("DeleteCategory", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/DeleteCategory
        new("DeleteSubcategory", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/DeleteSubcategory
        new("GenerateCategoryWithAI", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateCategoryWithAI
        new("GenerateCustomerWithAI", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/customers/generate-with-ai
        new("GenerateEmailContent", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/email/generate-ai-content
        new("GenerateMissingReceipts", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/orders/generate-missing-receipts
        new("GenerateOrderReceipts_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateOrderReceipts_HttpStart
        new("GenerateOrderWithAI", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateOrderWithAI
        new("GenerateOrdersBulk", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateOrdersBulk
        new("GenerateProductContent", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/products/generate-content
        new("GenerateProductEmbeddings_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateProductEmbeddings_HttpStart
        new("GenerateProductImages_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateProductImages_HttpStart
        new("GenerateProductImages_SingleProduct", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/products/{productId}/generate-images
        new("GenerateProductNameEmbeddings_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateProductNameEmbeddings
        new("GenerateProductReviewEmbeddings_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateProductReviewEmbeddings_HttpStart
        new("GenerateProductReviewsUsingAI_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GenerateProductReviewsUsingAI_HttpStart
        new("GeneratePromotion", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/GeneratePromotion
        new("GenerateReviewsWithReplies", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/products/{productId}/generate-reviews-with-replies
        new("GetCustomerCountryBreakdown", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/customer-country-breakdown
        new("GetCustomerMonthlyRevenue", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/customer-monthly-revenue
        new("GetCustomerRegionBreakdown", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/customer-region-breakdown
        new("GetCustomerStats", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/customer-stats
        new("GetCustomersWithDeliveredOrders", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/products/{productId}/customers-with-delivered-orders
        new("GetManufacturingAgentConfig", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/manufacturing/agent-config
        new("GetManufacturingAgentQueueStatus", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/manufacturing/agent-queue-status
        new("GetManufacturingAgentRuns", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/manufacturing/agent-runs
        new("GetManufacturingProposals", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/manufacturing/proposals
        new("GetOrderLines", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/orders/{orderId:int}/lines
        new("GetProductCatalog", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/product-catalog
        new("GetProductEligibleReviewerCount", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/products/{productId}/eligible-reviewer-count
        new("GetStoreById", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/stores/{storeId:int}
        new("GetStoreOrders", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/stores/{storeId:int}/orders
        new("GetStoreProducts", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/store-products
        new("GetStoreTerritories", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/store-territories
        new("GetStores", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/stores
        new("GetSubcategoryProductCount", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/GetSubcategoryProductCount
        new("GetTopSpenders", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/customers/top-spenders
        new("GetVerifiedReviewsStatus", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/generate-verified-reviews/status
        new("GetVerifiedReviewsSummary", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/generate-verified-reviews/summary
        new("ManufacturingWorkforceDetail", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/manufacturing/workforce/detail
        new("OrderDelivery_HttpTrigger", AccessTier.Internal, FunctionScopes.OrdersWrite, AccessMode.InternalOnly, null),  // /api/orders/delivery/trigger
        new("OrderPipeline_GetConfig", AccessTier.Internal, FunctionScopes.OrdersRead, AccessMode.InternalOnly, null),  // /api/orders/pipeline/config
        new("OrderPipeline_GetStatus", AccessTier.Internal, FunctionScopes.OrdersRead, AccessMode.InternalOnly, null),  // /api/orders/pipeline/status
        new("OrderPipeline_PromoteApproved", AccessTier.Internal, FunctionScopes.OrdersWrite, AccessMode.InternalOnly, null),  // /api/orders/pipeline/promote-approved
        new("OrderPipeline_PromotePending", AccessTier.Internal, FunctionScopes.OrdersWrite, AccessMode.InternalOnly, null),  // /api/orders/pipeline/promote-pending
        new("OrderPipeline_PutConfig", AccessTier.Internal, FunctionScopes.OrdersWrite, AccessMode.InternalOnly, null),  // /api/orders/pipeline/config
        new("PlaceStoreOrder", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/store-orders
        new("PostManufacturingAgentStep", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/agent-runs/{id}/step
        new("PutManufacturingAgentConfig", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/agent-config
        new("RefreshExchangeRates", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/exchange-rates/refresh
        new("RejectAllManufacturingProposals", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/proposals/reject-all
        new("RejectManufacturingProposal", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/manufacturing/proposals/{id}/reject
        new("ReportDashboardCounts", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/dashboard-counts
        new("ReportDiscountImpact", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/discount-impact
        new("ReportInventoryByCategory", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/inventory-by-category
        new("ReportMonthlyTrend", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/monthly-trend
        new("ReportOrdersByStatus", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/orders-by-status
        new("ReportProductPriceHistory", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/product-price-history
        new("ReportProductProfitability", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/product-profitability
        new("ReportProductProfitabilityDetail", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/product-profitability-detail
        new("ReportProfitabilityByCategory", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/profitability-by-category
        new("ReportRevenueByCategoryReport", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/revenue-by-category
        new("ReportRevenueByTerritory", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/revenue-by-territory
        new("ReportSalesTrends", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/sales-trends
        new("ReportSlowMovers", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/slow-movers
        new("ReportTopProducts", AccessTier.Internal, FunctionScopes.SalesRead, AccessMode.InternalOnly, null),  // /api/reporting/top-products
        new("ReviewModeration_StartAnalyzeApproveAll", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/reviews/moderation/start-analyze-approve-all
        new("ReviewModeration_Status", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/reviews/moderation/status
        new("SendCustomerEmail", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/customers/{customerId:int}/send-email
        new("SendPersonEmail", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/persons/{personId:int}/send-email
        new("ShipOrder", AccessTier.Internal, FunctionScopes.OrdersWrite, AccessMode.InternalOnly, null),  // /api/orders/{salesOrderId:int}/ship
        new("ShoppingSimulator_ClearQueue", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/shopping-simulator/clear-queue
        new("ShoppingSimulator_Results", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/shopping-simulator/results
        new("ShoppingSimulator_Start", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/shopping-simulator/start
        new("ShoppingSimulator_Status", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/shopping-simulator/status
        new("ShoppingSimulator_Stop", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/shopping-simulator/stop
        new("SimulationOrder_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/simulation/orders/start
        new("StartBatchVerifiedReviews", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/generate-verified-reviews/start
        new("SupplyChainGetConfig", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/supply/config
        new("SupplyChainInitialize", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/supply/initialize
        new("SupplyChainPutConfig", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/supply/config
        new("SupplyChainReorderAll", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/supply/reorder-all
        new("TranslateCategoryName", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/TranslateCategoryName
        new("TranslateLanguageFile_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/TranslateLanguageFile_HttpStart
        new("TranslateLanguageFile_Status", AccessTier.Internal, FunctionScopes.AdminRead, AccessMode.InternalOnly, null),  // /api/TranslateLanguageFile_Status
        new("TranslateLanguageFile_Terminate", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/TranslateLanguageFile_Terminate
        new("TranslateProductDescriptions_HttpStart", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/TranslateProductDescriptions_HttpStart
        new("TranslatePromotion", AccessTier.Internal, FunctionScopes.AdminWrite, AccessMode.InternalOnly, null),  // /api/TranslatePromotion
        new("WarehouseActiveOperations", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/active
        new("WarehouseDamageEvents", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/damage-events
        new("WarehouseGetDamageConfig", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/damage-config
        new("WarehouseGetSubcategoryConfig", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/subcategory-config
        new("WarehouseGetSupplierReceiveConfig", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/supplier-receive-config
        new("WarehouseInitialize", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/warehouse/initialize
        new("WarehouseMetrics", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/metrics
        new("WarehouseStatus", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/status
        new("WarehouseUpdateDamageConfig", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/warehouse/damage-config/{operationType}
        new("WarehouseUpdateSubcategoryConfig", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/warehouse/subcategory-config/{id}
        new("WarehouseUpdateSupplierReceiveConfig", AccessTier.Internal, FunctionScopes.ManufacturingWrite, AccessMode.InternalOnly, null),  // /api/warehouse/supplier-receive-config/{id}
        new("WarehouseWorkforce", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/workforce
        new("WarehouseWorkforceDetail", AccessTier.Internal, FunctionScopes.ManufacturingRead, AccessMode.InternalOnly, null),  // /api/warehouse/workforce/detail

        // ---- Tier M — v1-descoped MCP-proxied anonymous (44) ----
        new("BankDeposit", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/bank/deposit
        new("BankGetAccount", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/bank/accounts/{currencyCode}
        new("BankGetCurrencies", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/bank/currencies
        new("BankGetStatus", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/bank/status
        new("BankGetTransactions", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/bank/transactions
        new("BankGetTransactionsByCurrency", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/bank/transactions/{currencyCode}
        new("BankWithdraw", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/bank/withdraw
        new("CreateManufacturingProposal", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/proposals
        new("FinancialManufacturing", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/financials/manufacturing
        new("FinancialProcurement", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/financials/procurement
        new("FinancialSummary", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/financials/summary
        new("GetLocationConfig", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/location-config
        new("GetScrapConfig", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/scrap-config
        new("ManufacturingActive", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/active
        new("ManufacturingBegin", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/begin
        new("ManufacturingGetScrapEvents", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/scrap-events
        new("ManufacturingGetVendorQuality", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/vendor-quality
        new("ManufacturingGetVendorQualityById", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/vendor-quality/{vendorId:int}
        new("ManufacturingStatus", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/status
        new("ManufacturingStop", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/stop
        new("ManufacturingWorkforce", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/workforce
        new("PlanCatalog", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/catalog
        new("PlanCostAnalysis", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/cost/{productId:int}
        new("PlanCurrentManufacturingCost", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/cost/{productId:int}/current
        new("PlanFeasibility", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/feasibility/{productId:int}
        new("PlanFeasibilityAll", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/feasibility
        new("PlanOverstock", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/overstock
        new("PlanReorderRecommendations", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/reorder-recommendations
        new("PlanShortageForeceast", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/shortage-forecast
        new("PlanThinMargin", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/plan/thin-margin
        new("PutLocationConfig", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/location-config/{locationId:int}
        new("PutScrapConfig", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/manufacturing/scrap-config/{locationId:int}
        new("SimulatorsReset", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/simulators/reset
        new("SupplyChainCancelOrder", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/order/{orderId}
        new("SupplyChainGetCatalog", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/catalog
        new("SupplyChainGetCatalogByProduct", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/catalog/{productId:int}
        new("SupplyChainGetOrder", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/order/{orderId}
        new("SupplyChainGetOrderHistory", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/orders/history
        new("SupplyChainGetOrders", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/orders
        new("SupplyChainGetQuote", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/quote
        new("SupplyChainGetVendor", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/vendors/{vendorId}
        new("SupplyChainGetVendors", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/vendors
        new("SupplyChainPlaceOrder", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/order
        new("SupplyChainRestock", AccessTier.ProxiedAnonymous, null, AccessMode.Anonymous, null),  // /api/supply/restock/{vendorId}

    }.ToFrozenDictionary(p => p.FunctionName, StringComparer.Ordinal);

    /// <summary>Total number of classified HTTP routes.</summary>
    public static int Count => Policies.Count;

    /// <summary>All classified policies.</summary>
    public static IReadOnlyCollection<FunctionPolicy> All => Policies.Values;

    /// <summary>Returns the policy for a function name, or <c>null</c> if unclassified.</summary>
    public static FunctionPolicy? Find(string functionName) =>
        functionName is not null && Policies.TryGetValue(functionName, out var p) ? p : null;

    /// <summary>
    /// Returns the HTTP function names that have no policy entry. Used by a startup check to
    /// guarantee complete coverage (fail-closed): every HTTP-triggered function must be classified.
    /// </summary>
    public static IReadOnlyList<string> UnclassifiedHttpFunctions(IEnumerable<string> httpFunctionNames) =>
        httpFunctionNames.Where(n => !Policies.ContainsKey(n)).Distinct(StringComparer.Ordinal).ToList();
}
