-- AdventureWorks AI Enhancements
-- This script applies schema modifications to support AI-enhanced product data

-- Increase ProductDescription.Description column size to accommodate AI-generated content
-- Original: nvarchar(400) - Too small for enhanced descriptions (AI generates ~500+ characters)
-- Updated: nvarchar(2000) - Allows for detailed AI-generated product descriptions

-- Step 1: Drop the dependent indexed view
IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vProductAndDescription]'))
BEGIN
    DROP VIEW [Production].[vProductAndDescription];
    PRINT 'Dropped view Production.vProductAndDescription';
END;

GO

-- Step 2: Alter the Description column
ALTER TABLE [Production].[ProductDescription]
ALTER COLUMN [Description] [nvarchar](2000) NOT NULL;

PRINT 'ProductDescription.Description column updated to nvarchar(2000)';

GO

-- Step 3: Recreate the indexed view
CREATE VIEW [Production].[vProductAndDescription] 
WITH SCHEMABINDING 
AS 
-- View (indexed or standard) to display products and product descriptions by language.
SELECT 
    p.[ProductID] 
    ,p.[Name] 
    ,pm.[Name] AS [ProductModel] 
    ,pmx.[CultureID] 
    ,pd.[Description] 
FROM [Production].[Product] p 
    INNER JOIN [Production].[ProductModel] pm 
    ON p.[ProductModelID] = pm.[ProductModelID] 
    INNER JOIN [Production].[ProductModelProductDescriptionCulture] pmx 
    ON pm.[ProductModelID] = pmx.[ProductModelID] 
    INNER JOIN [Production].[ProductDescription] pd 
    ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID];

GO

-- Step 4: Recreate the clustered index on the view
CREATE UNIQUE CLUSTERED INDEX [IX_vProductAndDescription] ON [Production].[vProductAndDescription]([CultureID], [ProductID]);

GO

PRINT 'Successfully recreated view Production.vProductAndDescription with clustered index';

GO

-- Step 5: Expand Product.Color column to support creative AI-generated color names
-- Original: nvarchar(15) - Too restrictive for descriptive color names (e.g., "Glossy Carbon Fiber")
-- Updated: nvarchar(256) - Allows for detailed AI-generated color descriptions

ALTER TABLE [Production].[Product]
ALTER COLUMN [Color] [nvarchar](256) NULL;

PRINT 'Product.Color column updated to nvarchar(256)';

GO

-- Step 6: Add vector embedding column to ProductDescription for semantic search
-- Embeddings generated by text-embedding-3-small model (1536 dimensions)
-- Stored as VECTOR(1536) for Azure SQL Database native vector search
-- Size: 1536 dimensions × 4 bytes (float32) = 6144 bytes per embedding
-- Embeddings stored per language - enables multi-language semantic search

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductDescription]') AND name = 'DescriptionEmbedding')
BEGIN
    ALTER TABLE [Production].[ProductDescription]
    ADD [DescriptionEmbedding] VECTOR(1536) NULL;
    
    PRINT 'ProductDescription.DescriptionEmbedding column added for vector embeddings';
END
ELSE
BEGIN
    PRINT 'ProductDescription.DescriptionEmbedding column already exists - skipping';
END;

GO

-- Step 7: Create view for semantic product search across all languages
-- Joins Product -> ProductModel -> ProductModelProductDescriptionCulture -> ProductDescription
-- Enables language-specific vector similarity search via DAB API
-- Always drop and recreate to ensure view stays current with schema changes

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vProductSearch]'))
BEGIN
    DROP VIEW [Production].[vProductSearch];
END;

GO

CREATE VIEW [Production].[vProductSearch]
AS
SELECT 
        p.[ProductID],
        p.[Name] AS [ProductName],
        p.[ProductNumber],
        p.[Color],
        p.[Size],
        p.[Weight],
        p.[ListPrice],
        p.[ProductModelID],
        pm.[Name] AS [ProductModelName],
        pmx.[CultureID],
        pmx.[ProductDescriptionID],
        pd.[Description],
        pd.[DescriptionEmbedding],
        p.[ModifiedDate]
    FROM [Production].[Product] p
        LEFT JOIN [Production].[ProductModel] pm 
            ON p.[ProductModelID] = pm.[ProductModelID]
        LEFT JOIN [Production].[ProductModelProductDescriptionCulture] pmx 
            ON pm.[ProductModelID] = pmx.[ProductModelID]
        LEFT JOIN [Production].[ProductDescription] pd 
            ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID]
    WHERE p.[FinishedGoodsFlag] = 1;

GO
    
PRINT 'Created view Production.vProductSearch for multi-language semantic search';

GO

-- Step 8 and Step 9 (placeholder image cleanup and Primary flag) are NOT run here.
-- They run in seed-database.ps1 AFTER CSV loading, because ProductProductPhoto is populated
-- by ProductProductPhoto.csv and ProductProductPhoto-ai.csv later. Running the DELETE here
-- would hit an empty table; the CSV load would then re-insert ProductPhotoID=1 for many products.

-- Step 10: Add vector embedding column to ProductReview for semantic search
-- Embeddings generated by text-embedding-3-small model (1536 dimensions)
-- Stored as VECTOR(1536) for Azure SQL Database native vector search
-- Size: 1536 dimensions × 4 bytes (float32) = 6144 bytes per embedding
-- Enables semantic search across product review comments

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'CommentsEmbedding')
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD [CommentsEmbedding] VECTOR(1536) NULL;
    
    PRINT 'ProductReview.CommentsEmbedding column added for vector embeddings';
END
ELSE
BEGIN
    PRINT 'ProductReview.CommentsEmbedding column already exists - skipping';
END;

GO

-- Step 11: Add helpful vote counter to ProductReview
-- Tracks the number of "helpful" votes each review receives from customers
-- Defaults to 0 for all existing and new reviews
-- Useful for sorting and displaying most helpful reviews

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'HelpfulVotes')
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD [HelpfulVotes] INT NOT NULL DEFAULT 0;
    
    PRINT 'ProductReview.HelpfulVotes column added for tracking helpful votes';
END
ELSE
BEGIN
    PRINT 'ProductReview.HelpfulVotes column already exists - skipping';
END;

GO

-- Step 12: Add UserID column to ProductReview
-- Stores the BusinessEntityID to link reviews to user accounts in Person.Person table
-- Nullable to preserve existing reviews that don't have a UserID
-- Enables features like: preventing duplicate reviews, edit/delete own reviews, and tracking user activity

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'UserID')
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD [UserID] INT NULL;
    
    PRINT 'ProductReview.UserID column added for linking reviews to user accounts';
END
ELSE
BEGIN
    PRINT 'ProductReview.UserID column already exists - skipping';
END;

GO

-- Step 12a: Add foreign key constraint to Person.Person
-- Links UserID directly to the Person table via BusinessEntityID
-- This enforces referential integrity - reviews can only reference valid users

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[Production].[FK_ProductReview_Person_UserID]'))
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD CONSTRAINT [FK_ProductReview_Person_UserID]
    FOREIGN KEY ([UserID]) REFERENCES [Person].[Person]([BusinessEntityID]);
    
    PRINT 'Added foreign key constraint linking UserID to Person.BusinessEntityID';
END
ELSE
BEGIN
    PRINT 'Foreign key constraint FK_ProductReview_Person_UserID already exists - skipping';
END;

GO

-- Step 12b: Add unique constraint to prevent duplicate reviews per user
-- Ensures each user can only submit one review per product
-- Filtered to exclude legacy reviews that don't have a UserID

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'IX_ProductReview_ProductID_UserID_Unique')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [IX_ProductReview_ProductID_UserID_Unique]
    ON [Production].[ProductReview]([ProductID], [UserID])
    WHERE [UserID] IS NOT NULL;
    
    PRINT 'Added unique constraint on (ProductID, UserID) to prevent duplicate reviews';
END
ELSE
BEGIN
    PRINT 'Unique index IX_ProductReview_ProductID_UserID_Unique already exists - skipping';
END;

GO

-- Step 12c: Add index on UserID for query performance
-- Enables efficient lookup of all reviews by a specific user

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'IX_ProductReview_UserID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ProductReview_UserID]
    ON [Production].[ProductReview]([UserID])
    WHERE [UserID] IS NOT NULL;
    
    PRINT 'Added index on UserID for improved query performance';
END
ELSE
BEGIN
    PRINT 'Index IX_ProductReview_UserID already exists - skipping';
END;

GO

-- Step 13: Create view for semantic review search
-- Enables vector similarity search on product reviews via DAB API
-- Useful for finding reviews based on semantic meaning rather than keyword matching
-- Always drop and recreate to ensure view stays current with schema changes

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vReviewSearch]'))
BEGIN
    DROP VIEW [Production].[vReviewSearch];
END;

GO

CREATE VIEW [Production].[vReviewSearch]
AS
SELECT 
        pr.[ProductReviewID],
        pr.[ProductID],
        pr.[ReviewerName],
        pr.[ReviewDate],
        pr.[Rating],
        pr.[Comments],
        pr.[CommentsEmbedding],
        pr.[HelpfulVotes],
        pr.[UserID],
        pr.[ModifiedDate],
        p.[Name] AS [ProductName],
        p.[ProductNumber]
    FROM [Production].[ProductReview] pr
        INNER JOIN [Production].[Product] p 
            ON pr.[ProductID] = p.[ProductID];

GO

PRINT 'Created view Production.vReviewSearch for semantic review search';

GO

-- Step 14: Add index on ProductProductPhoto(ProductPhotoID) for photo lookups
-- The PK is (ProductID, ProductPhotoID), so lookups by ProductID are already fast.
-- Lookups by ProductPhotoID (e.g. joins from ProductPhoto, DAB relationship) need this index.
-- Without it, selecting many ProductPhoto rows can be very slow and cause timeouts/parsererror.

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[Production].[ProductProductPhoto]') AND name = 'IX_ProductProductPhoto_ProductPhotoID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_ProductProductPhoto_ProductPhotoID]
    ON [Production].[ProductProductPhoto]([ProductPhotoID]);
    PRINT 'Added index IX_ProductProductPhoto_ProductPhotoID for ProductPhoto lookups';
END
ELSE
BEGIN
    PRINT 'Index IX_ProductProductPhoto_ProductPhotoID already exists - skipping';
END;

GO

PRINT 'AI enhancements applied successfully';

GO

-- Step 15: Create Production.ProductName for multi-culture product name translations
-- Stores one translated name per product per culture, with a vector embedding for semantic search.
-- Embeddings generated by text-embedding-3-small (1536 dimensions), one per translated name.
-- Enables language-specific product name search and display across all 23 supported cultures.

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'[Production].[ProductName]'))
BEGIN
    CREATE TABLE [Production].[ProductName] (
        [ProductID]            INT              NOT NULL,
        [CultureID]            NCHAR(6)         NOT NULL,
        [Name]                 NVARCHAR(50)     NOT NULL,
        [ProductNameEmbedding] VECTOR(1536)     NULL,
        [rowguid]              UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL DEFAULT (NEWID()),
        [ModifiedDate]         DATETIME         NOT NULL DEFAULT (GETDATE()),
        CONSTRAINT [PK_ProductName_ProductID_CultureID]
            PRIMARY KEY CLUSTERED ([ProductID] ASC, [CultureID] ASC),
        CONSTRAINT [FK_ProductName_Product_ProductID]
            FOREIGN KEY ([ProductID]) REFERENCES [Production].[Product]([ProductID]),
        CONSTRAINT [FK_ProductName_Culture_CultureID]
            FOREIGN KEY ([CultureID]) REFERENCES [Production].[Culture]([CultureID])
    );
    PRINT 'Created table Production.ProductName for multi-culture product name translations';
END
ELSE
BEGIN
    PRINT 'Table Production.ProductName already exists - skipping';
END;

GO

-- Step 16: Update vProductSearch to LEFT JOIN ProductName and expose ProductNameEmbedding
-- Enables the semantic search function to access name embeddings alongside description embeddings.
-- Always drop and recreate to ensure view stays current with schema changes.

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vProductSearch]'))
BEGIN
    DROP VIEW [Production].[vProductSearch];
END;

GO

CREATE VIEW [Production].[vProductSearch]
AS
SELECT
        p.[ProductID],
        p.[Name] AS [ProductName],
        p.[ProductNumber],
        p.[Color],
        p.[Size],
        p.[Weight],
        p.[ListPrice],
        p.[ProductModelID],
        pm.[Name] AS [ProductModelName],
        pmx.[CultureID],
        pmx.[ProductDescriptionID],
        pd.[Description],
        pd.[DescriptionEmbedding],
        pn.[Name] AS [TranslatedProductName],
        pn.[ProductNameEmbedding],
        p.[ModifiedDate]
    FROM [Production].[Product] p
        LEFT JOIN [Production].[ProductModel] pm
            ON p.[ProductModelID] = pm.[ProductModelID]
        LEFT JOIN [Production].[ProductModelProductDescriptionCulture] pmx
            ON pm.[ProductModelID] = pmx.[ProductModelID]
        LEFT JOIN [Production].[ProductDescription] pd
            ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID]
        LEFT JOIN [Production].[ProductName] pn
            ON p.[ProductID] = pn.[ProductID] AND pn.[CultureID] = pmx.[CultureID]
    WHERE p.[FinishedGoodsFlag] = 1;

GO

PRINT 'Updated view Production.vProductSearch to include ProductName and ProductNameEmbedding';

GO

-- Step 17: Add IsModerated flag to ProductReview
-- Tracks whether a review has been reviewed and approved by AdventureWorks staff.
-- Defaults to 0 (unmoderated) for all new and existing reviews.

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'[Production].[ProductReview]') AND name = 'IsModerated')
BEGIN
    ALTER TABLE [Production].[ProductReview]
    ADD [IsModerated] BIT NOT NULL DEFAULT 0;

    PRINT 'ProductReview.IsModerated column added (default 0 = unmoderated)';
END
ELSE
BEGIN
    PRINT 'ProductReview.IsModerated column already exists - skipping';
END;

GO

-- Step 18: Create Production.ProductReviewReply table
-- Stores optional staff replies to product reviews, linked 1:many to ProductReview.
-- No CultureID: replies are always written in the language of the original review.

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID(N'[Production].[ProductReviewReply]'))
BEGIN
    CREATE TABLE [Production].[ProductReviewReply] (
        [ProductReviewReplyID] INT            IDENTITY(1,1) NOT NULL,
        [ProductReviewID]      INT            NOT NULL,
        [Reply]                NVARCHAR(3850) NOT NULL,
        [RepliedBy]            NVARCHAR(100)  NOT NULL CONSTRAINT [DF_ProductReviewReply_RepliedBy] DEFAULT ('AdventureWorks Team'),
        [ReplyDate]            DATETIME       NOT NULL CONSTRAINT [DF_ProductReviewReply_ReplyDate] DEFAULT (GETDATE()),
        [ModifiedDate]         DATETIME       NOT NULL CONSTRAINT [DF_ProductReviewReply_ModifiedDate] DEFAULT (GETDATE()),
        CONSTRAINT [PK_ProductReviewReply_ProductReviewReplyID]
            PRIMARY KEY CLUSTERED ([ProductReviewReplyID] ASC),
        CONSTRAINT [FK_ProductReviewReply_ProductReview]
            FOREIGN KEY ([ProductReviewID]) REFERENCES [Production].[ProductReview]([ProductReviewID])
    );

    CREATE NONCLUSTERED INDEX [IX_ProductReviewReply_ProductReviewID]
    ON [Production].[ProductReviewReply]([ProductReviewID]);

    PRINT 'Created table Production.ProductReviewReply with FK and index';
END
ELSE
BEGIN
    PRINT 'Table Production.ProductReviewReply already exists - skipping';
END;

GO

-- Step 19: Recreate vReviewSearch to include IsModerated
-- Always drop and recreate to keep view current with schema changes.

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vReviewSearch]'))
BEGIN
    DROP VIEW [Production].[vReviewSearch];
END;

GO

CREATE VIEW [Production].[vReviewSearch]
AS
SELECT
        pr.[ProductReviewID],
        pr.[ProductID],
        pr.[ReviewerName],
        pr.[ReviewDate],
        pr.[Rating],
        pr.[Comments],
        pr.[CommentsEmbedding],
        pr.[HelpfulVotes],
        pr.[UserID],
        pr.[IsModerated],
        pr.[ModifiedDate],
        p.[Name]          AS [ProductName],
        p.[ProductNumber]
    FROM [Production].[ProductReview] pr
        INNER JOIN [Production].[Product] p
            ON pr.[ProductID] = p.[ProductID];

GO

PRINT 'Recreated view Production.vReviewSearch with IsModerated column';

GO

-- Step 20: Create HumanResources.vEmployee view
-- DAB (Data API Builder) does not support hierarchyid columns (OrganizationNode, OrganizationLevel).
-- This view exposes the Employee table for the Manufacturing demo UI by excluding those columns.

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[HumanResources].[vEmployee]'))
BEGIN
    DROP VIEW [HumanResources].[vEmployee];
    PRINT 'Dropped existing HumanResources.vEmployee view';
END;

GO

CREATE VIEW [HumanResources].[vEmployee]
AS
SELECT
    [BusinessEntityID],
    [NationalIDNumber],
    [LoginID],
    [JobTitle],
    [BirthDate],
    [MaritalStatus],
    [Gender],
    [HireDate],
    [SalariedFlag],
    [VacationHours],
    [SickLeaveHours],
    [CurrentFlag],
    [rowguid],
    [ModifiedDate]
FROM [HumanResources].[Employee];

GO

PRINT 'Created view HumanResources.vEmployee (excludes hierarchyid columns for DAB compatibility)';

GO

-- Step 21: Create Production.vHelpMeChoose view
-- Comprehensive flat view for the Help Me Choose AI agent.
-- Combines finished-goods product attributes, culture-specific translated names and descriptions,
-- culture-specific category and subcategory names, inventory stock status, list price,
-- and aggregated product review ratings — one row per (ProductID, CultureID).
-- Key fields: CultureID + ProductID (unique per culture per product).

IF EXISTS (SELECT 1 FROM sys.views WHERE object_id = OBJECT_ID(N'[Production].[vHelpMeChoose]'))
BEGIN
    DROP VIEW [Production].[vHelpMeChoose];
    PRINT 'Dropped existing Production.vHelpMeChoose view';
END;

GO

CREATE VIEW [Production].[vHelpMeChoose]
AS
SELECT
    p.[ProductID],
    COALESCE(pn.[Name], p.[Name])                                       AS [ProductName],
    pd.[Description]                                                    AS [ProductDescription],
    p.[Color],
    p.[Size],
    CASE RTRIM(p.[ProductLine])
        WHEN 'R' THEN 'Road'
        WHEN 'M' THEN 'Mountain'
        WHEN 'T' THEN 'Touring'
        WHEN 'S' THEN 'Standard'
        ELSE NULL
    END                                                                 AS [ProductLine],
    CASE RTRIM(p.[Style])
        WHEN 'W' THEN 'Womens'
        WHEN 'M' THEN 'Mens'
        WHEN 'U' THEN 'Universal'
        ELSE NULL
    END                                                                 AS [Style],
    pcat.[Name]                                                         AS [Category],
    psc.[Name]                                                          AS [Subcategory],
    pmx.[CultureID],
    CAST(
        CASE WHEN ISNULL(inv.[TotalQuantity], 0) > 0 THEN 1 ELSE 0 END
        AS BIT
    )                                                                   AS [IsInStock],
    p.[ListPrice],
    CAST(ISNULL(rev.[AvgRating], 0.0) AS DECIMAL(3, 2))                AS [AverageRating],
    ISNULL(rev.[ReviewCount], 0)                                        AS [ReviewCount]
FROM [Production].[Product] p
    INNER JOIN [Production].[ProductModel] pm
        ON p.[ProductModelID] = pm.[ProductModelID]
    INNER JOIN [Production].[ProductModelProductDescriptionCulture] pmx
        ON pm.[ProductModelID] = pmx.[ProductModelID]
    INNER JOIN [Production].[ProductDescription] pd
        ON pmx.[ProductDescriptionID] = pd.[ProductDescriptionID]
    LEFT JOIN [Production].[ProductSubcategory] psc
        ON p.[ProductSubcategoryID] = psc.[ProductSubcategoryID]
        AND psc.[CultureID] = pmx.[CultureID]
    LEFT JOIN [Production].[ProductCategory] pcat
        ON psc.[ProductCategoryID] = pcat.[ProductCategoryID]
        AND pcat.[CultureID] = pmx.[CultureID]
    LEFT JOIN [Production].[ProductName] pn
        ON p.[ProductID] = pn.[ProductID]
        AND pn.[CultureID] = pmx.[CultureID]
    LEFT JOIN (
        SELECT [ProductID], SUM([Quantity]) AS [TotalQuantity]
        FROM [Production].[ProductInventory]
        GROUP BY [ProductID]
    ) inv
        ON p.[ProductID] = inv.[ProductID]
    LEFT JOIN (
        SELECT
            [ProductID],
            AVG(CAST([Rating] AS DECIMAL(10, 2))) AS [AvgRating],
            COUNT(*)                              AS [ReviewCount]
        FROM [Production].[ProductReview]
        GROUP BY [ProductID]
    ) rev
        ON p.[ProductID] = rev.[ProductID]
WHERE p.[FinishedGoodsFlag] = 1;

GO

PRINT 'Created view Production.vHelpMeChoose for the Help Me Choose AI agent';

GO
