namespace AdventureWorks.Auth;

/// <summary>
/// How a tool is authorized beyond the required scope.
/// </summary>
public enum ToolAccessMode
{
    /// <summary>Any caller holding <see cref="ToolPolicy.RequiredScope"/> may call the tool.</summary>
    Public,

    /// <summary>
    /// The tool exposes per-customer data. Consumers may only access their own records
    /// (the <see cref="ToolPolicy.OwnerArgument"/> is validated / injected against the
    /// caller's resolved CustomerID). Internal roles holding the scope are unrestricted.
    /// </summary>
    SelfOrInternal,

    /// <summary>
    /// Internal-only tool. Requires the scope AND a non-consumer category. Consumers are
    /// denied even if a token somehow carries the scope (defense in depth).
    /// </summary>
    InternalOnly,
}

/// <summary>Authorization policy for a single MCP tool.</summary>
/// <param name="Tool">The MCP wire name (snake_case) as generated by the SDK.</param>
/// <param name="RequiredScope">The single business-domain scope required to invoke the tool.</param>
/// <param name="Mode">Access mode (scope-only, ownership, or internal-only).</param>
/// <param name="OwnerArgument">
/// For <see cref="ToolAccessMode.SelfOrInternal"/>, the tool argument (camelCase) that carries the
/// customer identifier subject to ownership enforcement. Null for other modes.
/// </param>
public sealed record ToolPolicy(string Tool, string RequiredScope, ToolAccessMode Mode, string? OwnerArgument = null);

/// <summary>
/// The single, documented source of truth mapping every AdventureWorks MCP tool to a
/// business-domain scope and access mode. Startup validation asserts that every tool
/// discovered by the MCP server has an entry here (see <c>McpAuthorizationExtensions</c>).
///
/// Tool → scope matrix is reproduced in docs/features/mcp-oauth/TOOL_SCOPE_MATRIX.md.
/// </summary>
public static class ToolAuthorizationRegistry
{
    // NOTE: keys are the SDK-generated snake_case wire names, verified by reflection over
    // the built assembly. Method names convert PascalCase -> snake_case.
    private static readonly ToolPolicy[] Policies =
    {
        // ---- AdventureWorksMcpTools (19) ----
        new("get_customer_orders",              OAuthScopes.OrdersRead,      ToolAccessMode.SelfOrInternal, "customerId"),
        new("get_order_details",                OAuthScopes.OrdersRead,      ToolAccessMode.SelfOrInternal, "customerId"),
        new("find_complementary_products",      OAuthScopes.ProductsRead,    ToolAccessMode.Public),
        new("search_products",                  OAuthScopes.ProductsRead,    ToolAccessMode.Public),
        new("get_product_details",              OAuthScopes.ProductsRead,    ToolAccessMode.Public),
        new("get_personalized_recommendations", OAuthScopes.ProductsRead,    ToolAccessMode.SelfOrInternal, "customerId"),
        new("analyze_product_reviews",          OAuthScopes.ProductsRead,    ToolAccessMode.Public),
        new("check_inventory_availability",     OAuthScopes.InventoryRead,   ToolAccessMode.InternalOnly),
        new("get_products_for_promotion",       OAuthScopes.AdminRead,       ToolAccessMode.InternalOnly),
        new("get_categories_with_products",     OAuthScopes.ProductsRead,    ToolAccessMode.Public),
        new("get_active_promotions",            OAuthScopes.ProductsRead,    ToolAccessMode.Public),
        new("get_recent_customers_without_orders", OAuthScopes.CustomersRead, ToolAccessMode.InternalOnly),
        new("search_customers",                 OAuthScopes.CustomersRead,   ToolAccessMode.InternalOnly),
        new("get_top_selling_products",         OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_business_stats",               OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_top_customers",                OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_orders_by_status",             OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_sales_report_by_status",       OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_product_performance_summary",  OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),

        // ---- BankMcpTools (9) ----
        new("get_bank_status",                  OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_bank_account",                 OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_bank_transactions",            OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("bank_deposit",                     OAuthScopes.AdminWrite,      ToolAccessMode.InternalOnly),
        new("bank_withdraw",                    OAuthScopes.AdminWrite,      ToolAccessMode.InternalOnly),
        new("get_supported_currencies",         OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_financial_summary",            OAuthScopes.SalesRead,       ToolAccessMode.InternalOnly),
        new("get_procurement_transactions",     OAuthScopes.ManufacturingRead, ToolAccessMode.InternalOnly),
        new("get_manufacturing_financials",     OAuthScopes.ManufacturingRead, ToolAccessMode.InternalOnly),

        // ---- CustomerGeneratorMcpTools (2) ----
        new("generate_random_customer",            OAuthScopes.AdminWrite,   ToolAccessMode.InternalOnly),
        new("generate_random_customer_for_locale", OAuthScopes.AdminWrite,   ToolAccessMode.InternalOnly),

        // ---- SimulatorMcpTools (1) ----
        new("reset_all_simulators",             OAuthScopes.McpAdmin,        ToolAccessMode.InternalOnly),

        // ---- ManufacturingMcpTools (20) ----
        new("get_manufacturing_status",           OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_active_manufacturing_operations",OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_manufacturing_workforce",        OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_manufacturing_scrap_events",     OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_vendor_quality_report",          OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_scrap_configuration",            OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_location_configuration",         OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_production_feasibility",         OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_all_products_feasibility",       OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_product_cost_analysis",          OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_manufacturing_catalog_snapshot", OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_overstock_items",                OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_thin_margin_products",           OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_component_shortage_forecast",    OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_reorder_recommendations",        OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("begin_manufacturing_run",            OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
        new("stop_manufacturing",                 OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
        new("update_scrap_configuration",         OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
        new("update_location_configuration",      OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
        new("propose_manufacturing_run",          OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),

        // ---- SupplyChainMcpTools (11) ----
        new("get_supply_chain_vendors",           OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_vendor_details",                 OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_supply_catalog",                 OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_supply_quote",                   OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_active_supply_orders",           OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_supply_order_history",           OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("get_supply_order_details",           OAuthScopes.ManufacturingRead,  ToolAccessMode.InternalOnly),
        new("place_supply_order",                 OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
        new("cancel_supply_order",                OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
        new("restock_vendor_inventory",           OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
        new("propose_supply_order",               OAuthScopes.ManufacturingWrite, ToolAccessMode.InternalOnly),
    };

    private static readonly IReadOnlyDictionary<string, ToolPolicy> ByName =
        Policies.ToDictionary(p => p.Tool, StringComparer.Ordinal);

    /// <summary>All registered policies.</summary>
    public static IReadOnlyCollection<ToolPolicy> All => Policies;

    /// <summary>All tool names that have a policy.</summary>
    public static IReadOnlyCollection<string> ToolNames => ByName.Keys.ToArray();

    /// <summary>Looks up the policy for a tool, or null if unclassified.</summary>
    public static ToolPolicy? Find(string toolName) =>
        toolName is not null && ByName.TryGetValue(toolName, out var p) ? p : null;
}
