# Post-teardown script for cleanup
# This script removes local development artifacts after infrastructure is torn down

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "Running post-teardown cleanup..." -ForegroundColor Cyan

# Remove .env file generated by postup.ps1 for local debugging
try {
    $projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
    $envFile = Join-Path $projectRoot '.env'
    if (Test-Path -Path $envFile -PathType Leaf) {
        Write-Host "Removing generated .env file at $envFile" -ForegroundColor DarkCyan
        Remove-Item -Path $envFile -Force -ErrorAction Stop
        Write-Host ".env file removed." -ForegroundColor Green
    } else {
        Write-Host ".env file not present; nothing to remove." -ForegroundColor Gray
    }
} catch {
    Write-Warning "Failed to remove .env file: $($_.Exception.Message)"
}

# Remove API .env file if it exists
try {
    $apiEnvFile = Join-Path $projectRoot 'api' '.env'
    if (Test-Path -Path $apiEnvFile -PathType Leaf) {
        Write-Host "Removing API .env file at $apiEnvFile" -ForegroundColor DarkCyan
        Remove-Item -Path $apiEnvFile -Force -ErrorAction Stop
        Write-Host "API .env file removed." -ForegroundColor Green
    }
} catch {
    Write-Warning "Failed to remove API .env file: $($_.Exception.Message)"
}

Write-Host "Post-teardown cleanup completed." -ForegroundColor Green
